Route List
+------------------------------------+-------------------------------------------+--------+-------------------------------------------+
| Rule                               | Route                                     | Method | Name                                      |
+------------------------------------+-------------------------------------------+--------+-------------------------------------------+
| admin/login                        | admin/Auth/login                          | post   | admin/Auth/login                          |
| admin/user/info                    | admin/UserController/info                 | get    | admin/UserController/info                 |
| admin/logout                       | admin/Auth/logout                         | post   | admin/Auth/logout                         |
| admin/index/stat                   | admin/Index/stat                          | get    | admin/Index/stat                          |
| admin/index/todo                   | admin/Index/todo                          | get    | admin/Index/todo                          |
| admin/resource/category            | admin/ResourceController/category         | get    | admin/ResourceController/category         |
| admin/resource/category/save       | admin/ResourceController/saveCategory     | post   | admin/ResourceController/saveCategory     |
| admin/resource/category/delete     | admin/ResourceController/deleteCategory   | post   | admin/ResourceController/deleteCategory   |
| admin/resource/lists               | admin/ResourceController/lists            | get    | admin/ResourceController/lists            |
| admin/resource/save                | admin/ResourceController/save             | post   | admin/ResourceController/save             |
| admin/resource/delete              | admin/ResourceController/delete           | post   | admin/ResourceController/delete           |
| admin/resource/batch               | admin/ResourceController/batch            | post   | admin/ResourceController/batch            |
| admin/resource/move                | admin/ResourceController/move             | post   | admin/ResourceController/move             |
| admin/resource/upload              | admin/ResourceController/upload           | post   | admin/ResourceController/upload           |
| admin/resource/material            | admin/ResourceController/material         | get    | admin/ResourceController/material         |
| admin/resource/deleteMaterial      | admin/ResourceController/deleteMaterial   | post   | admin/ResourceController/deleteMaterial   |
| admin/resource/security            | admin/ResourceController/security         | post   | admin/ResourceController/security         |
| admin/member/level                 | admin/Member/level                        | get    | admin/Member/level                        |
| admin/member/level/save            | admin/Member/saveLevel                    | post   | admin/Member/saveLevel                    |
| admin/member/level/delete          | admin/Member/deleteLevel                  | post   | admin/Member/deleteLevel                  |
| admin/member/order                 | admin/Member/order                        | get    | admin/Member/order                        |
| admin/member/adjust                | admin/Member/adjust                       | post   | admin/Member/adjust                       |
| admin/user/lists                   | admin/UserController/lists                | get    | admin/UserController/lists                |
| admin/user/detail                  | admin/UserController/detail               | get    | admin/UserController/detail               |
| admin/user/add                     | admin/UserController/add                  | post   | admin/UserController/add                  |
| admin/user/save                    | admin/UserController/save                 | post   | admin/UserController/save                 |
| admin/user/disable                 | admin/UserController/disable              | post   | admin/UserController/disable              |
| admin/user/balance                 | admin/UserController/balance              | post   | admin/UserController/balance              |
| admin/user/points                  | admin/UserController/points               | post   | admin/UserController/points               |
| admin/user/reset_password          | admin/UserController/resetPassword        | post   | admin/UserController/resetPassword        |
| admin/user/download_records        | admin/UserController/downloadRecords      | get    | admin/UserController/downloadRecords      |
| admin/user/point_records           | admin/UserController/pointRecords         | get    | admin/UserController/pointRecords         |
| admin/user/invite_records          | admin/UserController/inviteRecords        | get    | admin/UserController/inviteRecords        |
| admin/point/rule                   | admin/Point/rule                          | get    | admin/Point/rule                          |
| admin/point/rule/save              | admin/Point/saveRule                      | post   | admin/Point/saveRule                      |
| admin/point/record                 | admin/Point/record                        | get    | admin/Point/record                        |
| admin/point/expire_notice          | admin/Point/expireNotice                  | post   | admin/Point/expireNotice                  |
| admin/invite/setting               | admin/Invite/setting                      | get    | admin/Invite/setting                      |
| admin/invite/setting/save          | admin/Invite/saveSetting                  | post   | admin/Invite/saveSetting                  |
| admin/invite/record                | admin/Invite/record                       | get    | admin/Invite/record                       |
| admin/invite/reward                | admin/Invite/reward                       | post   | admin/Invite/reward                       |
| admin/mall/category                | admin/Mall/category                       | get    | admin/Mall/category                       |
| admin/mall/category/save           | admin/Mall/saveCategory                   | post   | admin/Mall/saveCategory                   |
| admin/mall/category/delete         | admin/Mall/deleteCategory                 | post   | admin/Mall/deleteCategory                 |
| admin/mall/goods                   | admin/Mall/goods                          | get    | admin/Mall/goods                          |
| admin/mall/goods/save              | admin/Mall/saveGoods                      | post   | admin/Mall/saveGoods                      |
| admin/mall/goods/delete            | admin/Mall/deleteGoods                    | post   | admin/Mall/deleteGoods                    |
| admin/mall/goods/batch             | admin/Mall/batchGoods                     | post   | admin/Mall/batchGoods                     |
| admin/order/resource               | admin/Order/resource                      | get    | admin/Order/resource                      |
| admin/order/mall                   | admin/Order/mall                          | get    | admin/Order/mall                          |
| admin/order/ship                   | admin/Order/ship                          | post   | admin/Order/ship                          |
| admin/order/refund                 | admin/Order/refund                        | post   | admin/Order/refund                        |
| admin/order/export                 | admin/Order/export                        | post   | admin/Order/export                        |
| admin/ad/config                    | admin/Ad/config                           | get    | admin/Ad/config                           |
| admin/ad/config/save               | admin/Ad/saveConfig                       | post   | admin/Ad/saveConfig                       |
| admin/ad/stats                     | admin/Ad/stats                            | get    | admin/Ad/stats                            |
| admin/distributor/setting          | admin/DistributorController/setting       | get    | admin/DistributorController/setting       |
| admin/distributor/setting/save     | admin/DistributorController/saveSetting   | post   | admin/DistributorController/saveSetting   |
| admin/distributor/apply            | admin/DistributorController/apply         | get    | admin/DistributorController/apply         |
| admin/distributor/audit            | admin/DistributorController/audit         | post   | admin/DistributorController/audit         |
| admin/distributor/order            | admin/DistributorController/order         | get    | admin/DistributorController/order         |
| admin/distributor/withdraw         | admin/DistributorController/withdraw      | get    | admin/DistributorController/withdraw      |
| admin/distributor/withdraw_audit   | admin/DistributorController/withdrawAudit | post   | admin/DistributorController/withdrawAudit |
| admin/distributor/disable          | admin/DistributorController/disable       | post   | admin/DistributorController/disable       |
| admin/message/template             | admin/Message/template                    | get    | admin/Message/template                    |
| admin/message/template/save        | admin/Message/saveTemplate                | post   | admin/Message/saveTemplate                |
| admin/message/template/delete      | admin/Message/deleteTemplate              | post   | admin/Message/deleteTemplate              |
| admin/message/config               | admin/Message/config                      | get    | admin/Message/config                      |
| admin/message/config/save          | admin/Message/saveConfig                  | post   | admin/Message/saveConfig                  |
| admin/message/log                  | admin/Message/log                         | get    | admin/Message/log                         |
| admin/message/send                 | admin/Message/send                        | post   | admin/Message/send                        |
| admin/setting/basic                | admin/Setting/basic                       | get    | admin/Setting/basic                       |
| admin/setting/basic/save           | admin/Setting/saveBasic                   | post   | admin/Setting/saveBasic                   |
| admin/setting/payment              | admin/Setting/payment                     | get    | admin/Setting/payment                     |
| admin/setting/payment/save         | admin/Setting/savePayment                 | post   | admin/Setting/savePayment                 |
| admin/setting/security             | admin/Setting/security                    | get    | admin/Setting/security                    |
| admin/setting/security/save        | admin/Setting/saveSecurity                | post   | admin/Setting/saveSecurity                |
| admin/setting/upload               | admin/Setting/upload                      | post   | admin/Setting/upload                      |
| admin/complaint/lists              | admin/Complaint/lists                     | get    | admin/Complaint/lists                     |
| admin/complaint/handle             | admin/Complaint/handle                    | post   | admin/Complaint/handle                    |
| admin/complaint/stat               | admin/Complaint/stat                      | get    | admin/Complaint/stat                      |
| admin/stat/export                  | admin/Stat/export                         | post   | admin/Stat/export                         |
| admin/material/folder              | admin/MaterialController/folder           | get    | admin/MaterialController/folder           |
| admin/material/createFolder        | admin/MaterialController/createFolder     | post   | admin/MaterialController/createFolder     |
| admin/material/folder/renameFolder | admin/MaterialController/renameFolder     | post   | admin/MaterialController/renameFolder     |
| admin/material/folder/deleteFolder | admin/MaterialController/deleteFolder     | post   | admin/MaterialController/deleteFolder     |
| admin/material/list                | admin/MaterialController/list             | get    | admin/MaterialController/list             |
| admin/material/upload              | admin/MaterialController/upload           | post   | admin/MaterialController/upload           |
| admin/material/rename              | admin/MaterialController/rename           | post   | admin/MaterialController/rename           |
| admin/material/delete              | admin/MaterialController/delete           | post   | admin/MaterialController/delete           |
| api/login                          | api/Auth/login                            | post   | api/Auth/login                            |
| api/register                       | api/Auth/register                         | post   | api/Auth/register                         |
| api/forget                         | api/Auth/forget                           | post   | api/Auth/forget                           |
| api/captcha                        | api/Auth/captcha                          | get    | api/Auth/captcha                          |
| api/index                          | api/Index/index                           | get    | api/Index/index                           |
| api/resource/list                  | api/Resource/lists                        | get    | api/Resource/lists                        |
| api/resource/detail                | api/Resource/detail                       | get    | api/Resource/detail                       |
| api/member/levels                  | api/Member/levels                         | get    | api/Member/levels                         |
| api/user/info                      | api/User/info                             | get    | api/User/info                             |
| api/user/update                    | api/User/update                           | post   | api/User/update                           |
| api/user/balance_log               | api/User/balanceLog                       | get    | api/User/balanceLog                       |
| api/user/point_log                 | api/User/pointLog                         | get    | api/User/pointLog                         |
| api/user/sign                      | api/Point/sign                            | post   | api/Point/sign                            |
| api/resource/download              | api/Resource/download                     | post   | api/Resource/download                     |
| api/member/buy                     | api/Member/buy                            | post   | api/Member/buy                            |
| api/mall/goods                     | api/Mall/goods                            | get    | api/Mall/goods                            |
| api/mall/detail                    | api/Mall/detail                           | get    | api/Mall/detail                           |
| api/mall/order/create              | api/Mall/createOrder                      | post   | api/Mall/createOrder                      |
| api/order/list                     | api/Order/lists                           | get    | api/Order/lists                           |
| api/order/detail                   | api/Order/detail                          | get    | api/Order/detail                          |
| api/order/refund                   | api/Order/refund                          | post   | api/Order/refund                          |
| api/order/logistics                | api/Order/logistics                       | get    | api/Order/logistics                       |
| api/distributor/apply              | api/Distributor/apply                     | post   | api/Distributor/apply                     |
| api/distributor/center             | api/Distributor/center                    | get    | api/Distributor/center                    |
| api/distributor/orders             | api/Distributor/orders                    | get    | api/Distributor/orders                    |
| api/distributor/withdraw           | api/Distributor/withdraw                  | post   | api/Distributor/withdraw                  |
| api/distributor/withdraw_record    | api/Distributor/withdrawRecord            | get    | api/Distributor/withdrawRecord            |
| api/message/list                   | api/Message/lists                         | get    | api/Message/lists                         |
| api/message/detail                 | api/Message/detail                        | get    | api/Message/detail                        |
| api/message/read                   | api/Message/read                          | post   | api/Message/read                          |
| api/complaint/add                  | api/Complaint/add                         | post   | api/Complaint/add                         |
| api/complaint/list                 | api/Complaint/lists                       | get    | api/Complaint/lists                       |
| api/ad/impression                  | api/Ad/impression                         | post   | api/Ad/impression                         |
| api/ad/click                       | api/Ad/click                              | post   | api/Ad/click                              |
+------------------------------------+-------------------------------------------+--------+-------------------------------------------+
